name: 'Universal grafter'
description: 'Graft all the shared libraries.'
inputs:
  source_path:
    description: 'Absolute or relative path'
    required: true
  destination_path:
    description: 'Absolute or relative path'
    required: true
  dockcross:
    description: 'specify a dockcross container (only for linux)'
    required: false
    default: 'none'
  bitness:
    description: 'bitness'
    required: false
    default: 64
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9
    - run: pip install wheel==0.31.1
      shell: bash
    - name: Create dummy wheel from {{ inputs.source_path }}
      run: python ${{ github.action_path }}/create_wheel_local.py ${{ inputs.bitness }} ${{ inputs.dockcross }} ${{ inputs.source_path }}
      shell: bash
      id: create-wheel
    - name: Repair wheel
      run: |
        ${{ github.action_path }}/graft_linux.sh ${{ inputs.dockcross }} ${{steps.create-wheel.outputs.wheel_name}}
      shell: bash
    - name: Extract repaired wheel to {{ inputs.destination_path }}
      run: unzip ${{steps.create-wheel.outputs.wheel_name}} "dummy/**/*" -d ${{ inputs.destination_path }}/
      shell: bash

