on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - run: pip install
      - run: mkdir install
      - id: foo
        uses: jgillis/universal_grafter@master
        with:
          source_path: install
          destination_path: install_grafted
          dockcross: manylinux1-x64
          bitness: 64

