on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - run: mkdir install
      - id: foo
        uses: jgillis/universal_grafter@master
        with:
          source_path: install
          destination_path: install_grafted
          dockcross: manylinux1-x64
          bitness: 64

